### ISSUE TITLE
Where are the "specific version of the firmware" files?

### ISSUE THREAD

**Issue by darrylhadfield** [openmiko/openmiko#11]
Instructions indicate, "Download the specific version of the firmware you wish to install. Rename the firmware to demo.bin and put it in on the root of the microSD card."

Easy enough, but.. it's not clear to me where to donwload the specific version of firmware that I can then rename and use to mod the firmware on my Wyzecam v2.

Help?

**Comment by endertable** [comment]
https://github.com/openmiko/openmiko/releases/tag/v0.0.7rc1

**Comment by tachang** [comment]
I've updated the documentation with a picture so releases are easier to find.
