### ISSUE TITLE
RTSP not working

### ISSUE THREAD

**Issue by hillm5714** [openmiko/openmiko#16]
I have installed the latest release (Release v0.0.13) onto my WyzeCam V2. The stream and snapshot on port 8080 work just fine, but the RTSP feeds on 8554 do not work for me. Is there something else I need to configure other than loading the firmware, and adding the configured wpa_supplicant.conf file? Also, which of these feeds work best with OctoPrint? Is there anything else I should configure for this to work well with OctoPrint? Thanks in advance.

**Comment by qrimp** [comment]
I would suggest trying VLC. When I first got these cameras working I was trying to access the 8554 streams with Firefox and it kept thinking I was trying to search.
![image](https://user-images.githubusercontent.com/101055/107430507-186acf80-6ada-11eb-86c3-0d9db56f8902.png)

![image](https://user-images.githubusercontent.com/101055/107430665-510aa900-6ada-11eb-8c10-2249cd60c52d.png)

![image](https://user-images.githubusercontent.com/101055/107430749-70093b00-6ada-11eb-982c-49f9dec735f3.png)

**Comment by hillm5714** [comment]
That did the trick. Thanks for the help qrimp.
