### ISSUE TITLE
usb port(Type-A) not working ?

### ISSUE THREAD

**Issue by tuannt1531** [openmiko/openmiko#18]
I'm using a wyze camera V2. Today, I want to use usb Port as usb device mode. But, when I try to check the power of usb port, it not power on. This version of openmiko is support usb driver for wyze camera V2 as default? Thanks

**Comment by bill-mcgonigle** [comment]
Maybe it's this?

> Release v0.0.14
> @github-actions github-actions released this 2 days ago
> 
> General bug fixes and quality of life improvements.
> 
> Apparently the USB port wasn't working and a gpio pin needed to be activated to get power to the port.

**Comment by tachang** [comment]
Closing this since I worked with @tuannt1531 in Slack and the above fixes it for him. Thanks!!
