### ISSUE TITLE
Slack link expired

### ISSUE THREAD

**Issue by jetuser** [openmiko/openmiko#22]
Was trying to get some support but the slack links are expired and I'm unable to join.

**Comment by tachang** [comment]
Yikes just updated it. Really need to figure out a better way to do this.

**Comment by sedony23** [comment]
Again expired 😉

**Comment by tachang** [comment]
@sedony23 Thanks for letting me know:

https://join.slack.com/t/openmiko/shared_invite/zt-ra392gba-0Nmcn~XrKK3yfKfxiiLeLw
