### ISSUE TITLE
SXJ02ZM support?

### ISSUE THREAD

**Issue by eteixido1** [openmiko/openmiko#25]
Hello,
I'have been using openfang in my three SXJ02ZM. It is a 64GB T20 Ingenic and I like to know if i can migrate to Openmiko an how to do it because my cam only have a reset button.

Kind regards,

**Comment by tachang** [comment]
OpenMiko only works with 128MB ram devices. This is because I have too much stuff in the firmware right now for it to fit in 64 MB ram. I guess I could make a version that strips it down to minimal stuff but that would be hard.
