### ISSUE TITLE
SSH fingerprint not persistent 

### ISSUE THREAD

**Issue by NicolaiVdS** [openmiko/openmiko#3]
On every boot it generates a new ssh fingerprint

**Comment by NicolaiVdS** [comment]
FS seem to be in a non persistent mode ATM, just did the following test:
`touch test
reboot now`

after the reboot the test file is gone

**Comment by tachang** [comment]
Fixed in https://github.com/openmiko/openmiko/commit/e549157f8c4171cf04e993f869d768cfe431f15e
