### ISSUE TITLE
Subtle error. 

### ISSUE THREAD

**Issue by AbdulHamdy** [openmiko/openmiko#4]
In the releases page.. Your last release has what i can only assume are parameters of an rtsp stream. The resolution height is set to 1920. It should be 1080.

I do not code, otherwise I would've made a pull request myself. 
I hope I caught something you missed that was helpful. 

The wyze v2 cam has so much potential but is hindered by terrible software and the limitations of the SoC. You seem to be doing everyone a service. Good Luck.

**Comment by tachang** [comment]
Thank you. I'll go ahead and merge it!
