### ISSUE TITLE
How to set a static IP

### ISSUE THREAD

**Issue by marcobe** [openmiko/openmiko#59]
For some reason the camera Wyze Cam with 0.40 keeps jumping around on my network between IP addresses. My router assigns a dedicated IP address, but once and a while the camera will change it and jumps back for a few minutes. 

How can I setup a static internally?

**Comment by EQNish** [comment]
you can set the ip with;
`ifconfig wlan0 ###.###.###.### netmask ###.###.###.###`

how ever this does change on reboot, what I have been doing is making static reservations in my DHCP server once the cam in question comes on line, as I can than get the MAC address, which btw is different from the MAC printed on the camera once it's flashed
