### ISSUE TITLE
Wifi SSID with spaces

### ISSUE THREAD

**Issue by gcurtis79** [openmiko/openmiko#66]
v0.0.40
Fresh install
Multiple SD cards

Will not connect to WiFi SSID with spaces "QC Co-Lab"

Confirmed by adding a secondary SSID "QC_Co-Lab" and it connected.

**Comment by tachang** [comment]
Did you have double quotes in wpa_supplicant.conf?

**Comment by gcurtis79** [comment]
Yes. That was one of the first things I saw in reply to other WiFi issues. I used the example file, which already had double quotes.

This only occurred where I was testing & setting up the camera. The location I deployed to has no spaces, so it wasn't an issue after that.
