### ISSUE TITLE
[Q] Support for Wyze cam v2 HW revision

### ISSUE THREAD

**Issue by RohitJones** [openmiko/openmiko#7]
Does openmiko support the new hardware revision of the wyze cam v2 ?
There is an [open issue]( https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1616) at the Xiaomi-Dafang-Hacks repo for the same issue.

**Comment by RohitJones** [comment]
To answer my own question, Yes. openmiko is compatible with the new hw revision (FCC ID: 2ANJHWYZEC02) of the waze cam v2.
This was tested using the v1.0.0 prebuild binary.
There was the issue of the cam not obtaining a DHCP lease thus unable to stream anything over the network.

**Comment by tachang** [comment]
Hi. It should. FYI I've removed the v1.0.0 firmware because of bugginess. Please use the v0.0.5 one for now (or when I release a new one).
