### ISSUE TITLE
Can I use this with an Ingenic T21 camera?

### ISSUE THREAD

**Issue by felipecrs** [openmiko/openmiko#92]
Specifically this one: http://www.howellcam.com/product/38.html

Thanks for the awesome project. I'm wondering if I should try to flash in my camera with Ingenic T21 and not T20.

**Comment by CDX-24** [comment]
Hello there.

I also have several cameras with Ingenic T21 and ov2735b as the sensor (Wansview brand).
I am currently trying to alter the firmware but I think I will try with openmiko.
Also interested if some have experience and knowledge to share with this hardware !

Regards.

**Comment by martinbutt** [comment]
I have no specific experience, but if you follow these [updated instructions](https://github.com/openmiko/openmiko/blob/963f054ec55c0ebd92992cdb9e885194e7a5ad7b/doc/development.md), you'll have a Docker Buildroot environment to work in.

The code for the camera sensor is in [this repo](https://github.com/openmiko/ingenic_videocap), but is not part of the project I'm very familiar with.

In [this fork](https://github.com/q09029/ingenic_videocap) @q09029 was working on adding support for the T31. I don't know how far they got, but their commits might help you along.

**Comment by CDX-24** [comment]
Thank you I'll be sure to check this out ! 😄

**Comment by ryanjv755** [comment]
Hey CDX-24,

My friend and I are currently digging into this one. Let me know if we can help.

**Comment by gtxaspec** [comment]
Ingenic T21 and ov2735b now supported in openipc. FYI
